services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitnessdb
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness123
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
